# Tests for Exercise 11
# Written by your teacher. Do not edit this file.
# Run: pytest

from solution import double_all, add_to_total, remove_item, increment_all, merge

# --- Your teacher will fill in the test cases below ---
